export const Cars = [
    {
        id: 1,
        image:'https://vehicle-images.dealerinspire.com/374f-11002892/SALCP2FX0PH322151/136db88698a096cfaab1c8e8e2a1344a.jpg',
        name: '2023 Land Rover Discovery Sport',
        model: 'SE 4D Sport Utility',
        price: 'AED 240,400',
        colour: 'Black',
        mileage: '6,032 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 2,
        image:'https://vehicle-images.dealerinspire.com/8e31-11000947/thumbnails/large/SALCJ2FX2PH916015/00b510ecf7c3bac1d84501f5d9025871.jpg',
        name: '2023 Land Rover Discovery Sport',
        model: 'S 4D Sport Utility',
        price: 'AED 240,000',
        colour: 'White',
        mileage: '14 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 3,
        image:'https://media.cdn-jaguarlandrover.com/api/v2/images/72762/w/680',
        name: '2023 Land Rover Discovery Sport',
        model: 'Compact SUV',
        price: 'AED 240,325',
        colour: 'Green',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 4,
        image:'https://images.netdirector.auto/eyJrZXkiOiJuZHN0b2NrXC9pbWFnZXNcL3N0b2NrXC84ODNjZTYxZTY2Nzk3MzJlYzIxZDkxYjhmNjM3OGUwMDVkYzg4ZmQyXC9ORFMxNjIxOTMyNF8zNDU2MTJfMS5wbmciLCJidWNrZXQiOiJhdXRvZnMiLCJsYXN0X21vZGlmaWVkIjoiMTY4NTU5NTUwOCIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDQwLCJoZWlnaHQiOjI0OCwiZml0IjoiY29udGFpbiIsImJhY2tncm91bmQiOnsiciI6MjU1LCJnIjoyNTUsImIiOjI1NSwiYWxwaGEiOjF9fX19',
        name: 'Land Rover Defender L663',
        model: 'DEFENDER 130 HSE P400',
        price: 'AED 416,850',
        colour: 'Black',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 5,
        image:'https://images.netdirector.auto/eyJrZXkiOiJuZHN0b2NrXC9pbWFnZXNcL3N0b2NrXC84ODNjZTYxZTY2Nzk3MzJlYzIxZDkxYjhmNjM3OGUwMDVkYzg4ZmQyXC9ORFMxNjIzNjg0N18zNDU1NzZfMS5wbmciLCJidWNrZXQiOiJhdXRvZnMiLCJsYXN0X21vZGlmaWVkIjoiMTY4NTk0MzA1NyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDQwLCJoZWlnaHQiOjI0OCwiZml0IjoiY29udGFpbiIsImJhY2tncm91bmQiOnsiciI6MjU1LCJnIjoyNTUsImIiOjI1NSwiYWxwaGEiOjF9fX19',
        name: 'Land Rover Defender L663',
        model: 'DEFENDER 130 HSE P400',
        price: 'AED 427,560',
        colour: 'Black',
        mileage: 'Mileage 3,000 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 6,
        image:'https://images.netdirector.auto/eyJrZXkiOiJuZHN0b2NrXC9pbWFnZXNcL3N0b2NrXC84ODNjZTYxZTY2Nzk3MzJlYzIxZDkxYjhmNjM3OGUwMDVkYzg4ZmQyXC9TQUxFQTZCRTJOMjA3NjcxMl8xLmpwZyIsImJ1Y2tldCI6ImF1dG9mcyIsImxhc3RfbW9kaWZpZWQiOiIxNjgzODE3MTY3IiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo0NDAsImhlaWdodCI6MjQ4LCJmaXQiOiJjb250YWluIiwiYmFja2dyb3VuZCI6eyJyIjoyNTUsImciOjI1NSwiYiI6MjU1LCJhbHBoYSI6MX19fX0=',
        name: '2022 Land Rover New Defender',
        model: 'Defender 90 V8 P525 (A)',
        price: 'AED 549,000',
        colour: 'Black',
        mileage: 'Mileage 16,404 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 7,
        image:'https://images.netdirector.auto/eyJrZXkiOiJuZHN0b2NrXC9pbWFnZXNcL3N0b2NrXC84ODNjZTYxZTY2Nzk3MzJlYzIxZDkxYjhmNjM3OGUwMDVkYzg4ZmQyXC8xNTk5NDEwOF8xLmpwZyIsImJ1Y2tldCI6ImF1dG9mcyIsImxhc3RfbW9kaWZpZWQiOiIxNjgxODE0MzcwIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo0NDAsImhlaWdodCI6MjQ4LCJmaXQiOiJjb250YWluIiwiYmFja2dyb3VuZCI6eyJyIjoyNTUsImciOjI1NSwiYiI6MjU1LCJhbHBoYSI6MX19fX0=',
        name: '2023 Land Rover New Defender',
        model: 'DEFENDER 130 SE P400 (A)',
        price: 'AED 579,000',
        colour: 'White',
        mileage: 'Mileage 249 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 8,
        image:'https://images.netdirector.auto/eyJrZXkiOiJuZHN0b2NrXC9pbWFnZXNcL3N0b2NrXC84ODNjZTYxZTY2Nzk3MzJlYzIxZDkxYjhmNjM3OGUwMDVkYzg4ZmQyXC9ORFMxNjIxODAxMV8zNDg2MjlfMS5wbmciLCJidWNrZXQiOiJhdXRvZnMiLCJsYXN0X21vZGlmaWVkIjoiMTY4NTUzNTc4MCIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDQwLCJoZWlnaHQiOjI0OCwiZml0IjoiY29udGFpbiIsImJhY2tncm91bmQiOnsiciI6MjU1LCJnIjoyNTUsImIiOjI1NSwiYWxwaGEiOjF9fX19',
        name: 'Land Rover Defender L663',
        model: 'DEFENDER 130 SE P400',
        price: 'AED 411,560',
        colour: 'Silver',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 9,
        image:'https://ymimg1.b8cdn.com/resized/car_model/8913/pictures/9015271/webp_listing_main_8127.webp',
        name: '2023 Land Rover Range Rover Velar',
        model: '3.0L V6 R-Dynamic HSE (340 PS)',
        price: 'AED 320,000',
        colour: 'Silver',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 10,
        image:'https://static.cargurus.com/images/forsale/2023/05/09/18/10/2023_land_rover_range_rover_velar-pic-3265066338627122051-1024x768.jpeg',
        name: '2022 Land Rover Range Rover Velar',
        model: '',
        price: 'AED 419,000',
        colour: 'Grey',
        mileage: 'Mileage 250 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 11,
        image:'https://s1.cdn.autoevolution.com/images-webp/news/2022-range-rover-velar-gets-updates-a-special-edition-and-more-options-167556-7.jpg.webp',
        name: '2022 Land Rover Range Rover Velar',
        model: 'Auric Edition',
        price: ' AED 300,000',
        colour: 'Brown',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 12,
        image:'https://vehicle-images.dealerinspire.com/7b16-11000947/SALYV2FUXPA363607/609c725a1d4d593827847b3c7a5c6471.jpg',
        name: 'New 2023 Land Rover Range Rover Velar',
        model: 'HST 4D Sport Utility',
        price: 'AED 307,303',
        colour: 'red',
        mileage: '14 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 13,
        image:'https://vehicle-images.dealerinspire.com/3211-11000947/thumbnails/large/SALYV2FU7PA363001/85be57ccae887a18abb6f7c30eb7ddd8.jpg',
        name: 'New 2023 Land Rover Range Rover Velar',
        model: 'HST 4D Sport Utility',
        price: 'AED 307,303',
        colour: 'Black',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 14,
        image:'https://vehicle-images.dealerinspire.com/01bc-11000947/thumbnails/large/SALYV2FU5PA364051/96293ca1211cd8678e328731d51c9940.jpg',
        name: 'New 2023 Land Rover Range Rover Velar',
        model: 'HST 4D Sport Utility',
        price: 'AED 307,303',
        colour: 'White',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 15,
        image:'https://di-uploads-pod12.dealerinspire.com/landroverlouisville/uploads/2022/04/2023-Range-Rover-Thumb.jpg',
        name: 'New 2023 Land Rover Range Rover',
        model: 'P400 SE',
        price: 'AED 960,000',
        colour: 'Gold',
        mileage: '14 kmph',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 16,
        image:'https://dealerinspire-image-library-prod.s3.us-east-1.amazonaws.com/images/4QxtFDrP8DJpwQb9cpABRl8m7A6vwAByuS8YRKEl.jpg',
        name: 'New 2023 Land Rover Range Rover',
        model: 'P400 SE LWB',
        price: 'AED 960,000',
        colour: 'White',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 17,
        image:'https://www.cnet.com/a/img/resize/bca5bec01c8e29da793e9da734d0e20059942e17/hub/2022/04/06/34a269a6-aff7-404f-80d5-c45aa525e01c/ogi1-2023-range-rover-002.jpg?auto=webp&fit=crop&height=900&width=1200',
        name: 'New 2023 Land Rover Range Rover',
        model: 'P400 SE',
        price: 'AED 960,000',
        colour: 'Green',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 18,
        image:'https://paultan.org/image/2020/07/2021-Range-Rover-SV-Autobiography-Black-1.jpg',
        name: 'New 2023 Land Rover Range Rover',
        model: 'P400 SE LWB',
        price: 'AED 960,000',
        colour: 'Black',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 19,
        image:'https://www.cnet.com/a/img/resize/691bd638a1893de92e0eb404c9621b7726e4ab4d/hub/2021/10/22/6774b354-4042-457f-87cd-4e2fdfd393fc/2022-land-rover-range-rover-sv-23.jpg?auto=webp&width=1200',
        name: 'New 2023 Land Rover Range Rover',
        model: 'P400 SE',
        price: 'AED 960,000',
        colour: 'Red',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },  
     {
        id: 20,
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn-siGNb1AaTgPkdbcO_X_ZtGz3K10A25r2IdhBZEZvQolVWGX4hHBIE2PF3YPzdQbJ_M&usqp=CAU',
        name: '2022 Land Rover Range Rover',
        model: 'Vogue',
        price: 'AED 589,200',
        colour: 'Blue',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
        id: 21,
        image:'https://s1.cdn.autoevolution.com/images/news/dark-manhart-vogue-rv-650-shows-the-power-of-gold-contrast-on-2022-range-rover-185156_1.jpg',
        name: '2022 Land Rover Range Rover',
        model: 'Dark Manhart Vogue Rv 650',
        price: 'AED 650,000',
        colour: 'Black and Gold',
        mileage: '14 kmph ',
        fuelType: 'Petrol',
        transmission: 'Automatic',
    },
    {
    id: 22,
    image:'https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/image_from_ios_8_11.jpg?itok=u9aofJxL',
    name: '2022 Land Rover Range Rover',
    model: '',
    price: 'AED 650,000',
    colour: 'Wine',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 23,
    image:'https://images.cars.com/cldstatic/wp-content/uploads/land-rover-range-rover-2022-001-exterior-front-angle-suv-white.jpg',
    name: '2022 Land Rover Range Rover',
    model: '',
    price: 'AED 650,000',
    colour: 'White',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 24,
    image:'https://automanager.blob.core.windows.net/wmphotos/033666/08f32e20d37b466aaf4cb30dc2b5ba8b/9bdeaad450_1280.jpg',
    name: '2022 Land Rover Range Rover Sport',
    model: 'HSE Silver Edition',
    price: 'AED 450,000',
    colour: 'White',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 25,
    image:'https://dealer-content.s3.amazonaws.com/images/models/land-rover/2022/range-rover-sport/colors/eiger-grey-metallic.png',
    name: '2022 Land Rover Range Rover Sport',
    model: 'HSE Silver Edition',
    price: 'AED 450,000',
    colour: 'Grey',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 26,
    image:'https://cars.usnews.com/pics/size/390x290/images/Auto/izmo/i159614570/2022_land_rover_range_rover_angularfront.jpg',
    name: '2022 Land Rover Range Rover Sport',
    model: 'HSE',
    price: 'AED 420,000',
    colour: 'Black',
    mileage: '523 kmph',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 27,
    image:'https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20221208121219__HSS4976.jpg&w=700&q=90&c=1',
    name: '2023 Land Rover Range Rover Sport',
    model: '5.0L V8 HSE Dynamic (525PS)',
    price: 'AED 520,130',
    colour: 'Red',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 28,
    image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU1dfSRwggm62r148x__d27_KYGBdNelOWJA&usqp=CAU',
    name: '2023 Land Rover Range Rover Sport',
    model: '5.0L V8 HSE Dynamic (525PS)',
    price: 'AED 520,130',
    colour: 'Gold',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 29,
    image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSRo_B9JU4C-7EKrT_PyuGRIKsfW0OK6p9vChOjkeqhYi-ySyfDsKxBDt5LIcD7vnLpoY&usqp=CAU',
    name: '2023 Land Rover Range Rover Sport',
    model: 'P400 Dynamic SE',
    price: 'AED 550,130',
    colour: 'White',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 30,
    image:'https://vehicle-images.dealerinspire.com/c3c5-11000953/thumbnails/large/SAL1L9FU0PA115317/8cfd6346565f127c322f84fe0cd5983e.jpg',
    name: '2023 Land Rover Range Rover Sport',
    model: 'SE Dynamic 4D',
    price: 'AED 550,130',
    colour: 'Black',
    mileage: '14 kmph',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 31,
    image:'https://www.ccarprice.com/products/LandRover_Range_Rover_Evoque_P250_SE_2022.jpg',
    name: '2022 Land Rover Range Rover Evoque',
    model: 'P250 SE',
    price: 'AED 180,000',
    colour: 'Red',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 32,
    image:'https://media.ed.edmunds-media.com/land-rover/range-rover-evoque/2022/oem/2022_land-rover_range-rover-evoque_4dr-suv_p250-se_fq_oem_1_1600.jpg',
    name: '2022 Land Rover Range Rover Evoque',
    model: 'LWB',
    price: 'AED 180,000',
    colour: 'White',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 33,
    image:'https://media.cdn-jaguarlandrover.com/api/v2/images/73181/w/680',
    name: '2022 Land Rover Range Rover Evoque',
    model: 'LWB',
    price: 'AED 178,000',
    colour: 'Black',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 34,
    image:'https://img.gumtree.co.za/api/v1/za-pt10-ads/images/db/db345c6e-e76d-4101-8a64-3fe6002dfc84?rule=s-I85.auto',
    name: '2023 Land Rover Range Rover Evoque',
    model: 'MY212.0 D D200 R-Dynamic HSE',
    price: 'AED 320,000',
    colour: 'White',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 35,
    image:'https://www.motortrend.com/uploads/2022/08/2023-Land-Rover-Range-Rover-Evoque-P250-3.jpg',
    name: '2023 Land Rover Range Rover Evoque',
    model: 'HSE',
    price: 'AED 320,000',
    colour: 'Grey',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 36,
    image:'https://d3s8goeblmpptu.cloudfront.net/mrp/land-rover/2023/range-rover-evoque/2023-land-rover-range-rover-evoque_landing-6.jpg',
    name: '2023 Land Rover Range Rover Evoque',
    model: 'HSE',
    price: 'AED 320,000',
    colour: 'Red',
    mileage: '535 kmph',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 37,
    image:'https://www.motortrend.com/uploads/2021/10/2023-Land-Rover-Discovery-Metropolitan-Edition-12.jpg',
    name: '2023 Land Rover Discovery',
    model: 'P300',
    price: 'AED 330,000',
    colour: 'Brown',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 38,
    image:'https://vehicle-images.dealerinspire.com/fca4-11000947/thumbnails/large/SALRT2EX5P2480589/12135f2cfc61cb5fd0f522d91b28da17.jpg',
    name: '2023 Land Rover Discovery',
    model: 'P300 S R-Dynamic 4D',
    price: 'AED 330,000',
    colour: 'Black',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 39,
    image:'https://vehicle-images.dealerinspire.com/e5d7-110008838/SALRM4EU9P2474065/ef664d51db6bf5701fcb2a190c7b4f65.jpg',
    name: '2023 Land Rover Discovery',
    model: 'P360 S R-Dynamic 4D',
    price: 'AED 330,000',
    colour: 'White',
    mileage: '15 kmph',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 40,
    image:'https://www.motorbeam.com/wp-content/uploads/2022-Land-Rover-Discovery.jpg',
    name: '2022 Land Rover Discovery',
    model: 'P300',
    price: 'AED 240,000',
    colour: 'Gold',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},  
 {
    id: 41,
    image:'https://9512242f70552c1e6eb6-fe74cd567ea2f1228f846834bd67571e.ssl.cf1.rackcdn.com/ldm-images/land-rover/discovery/2021-Land-Rover-Discover-color-Fugi-White.png',
    name: '2022 Land Rover Discovery',
    model: 'P300',
    price: 'AED 240,000',
    colour: '   White',
    mileage: '0 km',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
{
    id: 42,
    image:'Sold',
    name: 'New 2023 Land Rover Range Rover',
    model: 'P400 SE',
    price: 'AED 960,000',
    colour: 'Navy Blue',
    mileage: '14 kmph ',
    fuelType: 'Petrol',
    transmission: 'Automatic',
},
    
]

export const userInputs = [
    {
        id: 'username',
        label: 'Username',
        type: 'text',
        placeholder: 'john_doe',
    },
    {
        id: 'displayName',
        label: 'Name and Surname',
        type: 'text',
        placeholder: 'John Doe',
    },
    {
        id: 'email',
        label: 'Email',
        type: 'mail',
        placeholder: 'john_doe@gmail.com'
    },
    {
        id: 'password',
        label: 'Password',
        type: 'password', 
    },
    {
        id: 'country',
        label: 'Country',
        type: 'text',
        placeholder: 'USA',
    },
]

